# Generated by Django 5.2.8 on 2025-12-04 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_producto_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='stock_critico',
            field=models.BooleanField(default=False),
        ),
    ]
