# Generated by Django 5.2.8 on 2025-12-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0015_venta_metodo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
