# Generated by Django 6.0 on 2025-12-18 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0016_venta_descuento'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (Reposición)'), ('salida', 'Salida (Venta)')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.producto')),
            ],
        ),
    ]
